version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout #Circle CI
      - run:
          name: The First Step
          command: gradle test
      - run:
          name: The second step
          command: gradle jar
      - store_artifacts:
          path: build/libs
          destination: prefix
      - store_test_results: #Circle CI
          path: build/test-results
      