version: 2.0

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - package:
          requires: 
          - test
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout #Circle CI
      - run:
          name: The First Step
          command: gradle test
      - run:
          name: The second step
          command: gradle jar
      - store_test_results: #Circle CI
          path: build/test-results
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout #Circle CI
      - run:
          name: The second step
          command: gradle jar
      - store_artifacts: #Circle CI
          path: build/libs
          destination: prefix
      