version: 2.0

workflows:
  version: 2
  test_and_package:
    jobs:
      - test
      - package:
          requires: 
          - test
      - dockerize:
          requires:
            - package
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout #Circle CI
      - run:
          name: Testerized
          command: gradle test
      - store_test_results: #Circle CI
          path: build/test-results
      - persist_to_workspace:
          root: .
          paths:
            - .
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Jarishered
          command: gradle jar
      - store_artifacts: #Circle CI
          path: build/libs
          destination: prefix
      - persist_to_workspace:
          root: .
          paths:
            - .
  dockerize:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     # build the application image
      - run: docker build -t $DOCKER_USER/myapp:$CIRCLE_SHA1 .
     # deploy the image
      - run: docker push $DOCKER_USER/myapp:$CIRCLE_SHA1

  

      
      